version: "3.9"

services:
  leo:
    build: .
    container_name: leo-network

    privileged: true

    stdin_open: true
    tty: true

    network_mode: host

    volumes:
      - ./:/app

    working_dir: /app

    command: bash